$(document).ready(function () {
  var teamsData = getTeams();
  localStorage.getItem("totalTeamData")
    ? ""
    : localStorage.setItem("totalTeamData", JSON.stringify(teamsData));
  teamsData = JSON.parse(localStorage.getItem("totalTeamData"));

  function createTeamCard(id, teamLogoUrl, teamName, winCount, teamData) {
    var mainDivHome = $("#teamList");

    var teamCardDiv = $("<div>");
    teamCardDiv.attr("class", "cardTeam");
    teamCardDiv.attr("id", id);

    var teamLogoDiv = $("<div>");
    teamLogoDiv.attr("class", "teamLogoDiv");
    var teamLogoImage = $("<img>");
    teamLogoImage.attr("class", "teamLogo");
    teamLogoImage.attr("src", teamLogoUrl);

    var teamDetailsDiv = $("<div>");
    teamDetailsDiv.attr("class", "teamDetails");
    var teamNamePara = $("<p>");
    teamNamePara.attr("class", "teamName");
    teamNamePara.html(teamName);
    var teamWinCountPara = $("<p>");
    teamWinCountPara.attr("class", "winCount");
    teamWinCountPara.html("IPL Trophie's: " + winCount);

    teamLogoDiv.append(teamLogoImage);
    teamDetailsDiv.append(teamNamePara, teamWinCountPara);
    teamCardDiv.append(teamLogoDiv, teamDetailsDiv);
    teamCardDiv.click(function () {
      $(location).attr("href", "./team.html");
      localStorage.setItem("teamData", JSON.stringify(teamData));
    });
    mainDivHome.append(teamCardDiv);
  }
  for (var i = 0; i < teamsData.length; i++) {
    createTeamCard(
      teamsData[i].id,
      teamsData[i].teamLogoUrl,
      teamsData[i].teamName.toUpperCase(),
      teamsData[i].noOfWins,
      teamsData[i]
    );
  }
  $("#ct").click(function () {
    var teamName = prompt("Enter team name?");
    var key = "";
    for (var i = 0; i < teamName.split(" ").length; i++) {
      key += teamName.split(" ")[i][0].toUpperCase();
    }
    var totalWon = prompt("Enter total no of times team won IPL?");
    var topBatsman = prompt("Enter top batsmen?");
    var topBowler = prompt("Enter top bowler?");
    var totalNoOfPlayers = prompt("Enter total no of players?");
    var teamLogoUrl = prompt("Enter team logo url?");
    var teamId = prompt("Enter team ID?");
    var newTeamObj = {
      id: teamId,
      teamName: teamName,
      key: key,
      noOfWins: totalWon,
      topBatsman: topBatsman,
      topBowler: topBowler,
      totalPlayer: totalNoOfPlayers,
      teamLogoUrl: teamLogoUrl,
      players: [],
    };
    teamsData.push(newTeamObj);
    localStorage.setItem("totalTeamData", JSON.stringify(teamsData));
    createTeamCard(teamId, teamLogoUrl, teamName, totalWon, newTeamObj);
  });

  $("#searchIco").click(function () {
    var searchKey = $("#search-box")[0].value;
    for (var j = 0; j < teamsData.length; j++) {
      if (teamsData[j].key == searchKey.toUpperCase()) {
        $("#search-box")[0].value = "";
        $(location).attr("href", "./team.html#playersList");
        localStorage.setItem("teamData", JSON.stringify(teamsData[j]));
        break;
      } else if (j == teamsData.length - 1) {
        alert("Team Not Found!");
      }
    }
  });

  function getTeams() {
    var cskPlayers = [
      {
        id: 0,
        playerName: "Bhagat Verma",
        from: "CSK",
        price: "20 Lac",
        isPlaying: true,
        description: "All-Rounder",
        imgUrl: "./images/Teams/CSK/Bhagat Verma.png",
      },
      {
        id: 1,
        playerName: "Cheteshwar Pujara",
        from: "CSK",
        price: "50 Lac",
        isPlaying: true,
        description: "Batsman",
        imgUrl: "./images/Teams/CSK/cheteshwar pujara.png",
      },
      {
        id: 2,
        playerName: "Deepak Chahar",
        from: "CSK",
        price: "80 Lac",
        isPlaying: true,
        description: "Bowler",
        imgUrl: "./images/Teams/CSK/deepak chahar.png",
      },
      {
        id: 3,
        playerName: "Dwane Bravo",
        from: "CSK",
        price: "92 Lac",
        isPlaying: true,
        description: "Bowler",
        imgUrl: "./images/Teams/CSK/dwane bravo.png",
      },
      {
        id: 4,
        playerName: "Faf Du Plessis",
        from: "CSK",
        price: "1.6 Cr",
        isPlaying: true,
        description: "Batsman",
        imgUrl: "./images/Teams/CSK/faf du plessis.png",
      },
      {
        id: 5,
        playerName: "Hari Nishaant",
        from: "CSK",
        price: "20 Lac",
        isPlaying: true,
        description: "Batsman",
        imgUrl: "./images/Teams/CSK/Hari Nishaant.png",
      },
      {
        id: 6,
        playerName: "Harishankar Readdy",
        from: "CSK",
        price: "20 Lac",
        isPlaying: true,
        description: "Bowler",
        imgUrl: "./images/Teams/CSK/harishankar Readdy.png",
      },
      {
        id: 7,
        playerName: "Imran Tahir",
        from: "CSK",
        price: "1 Cr",
        isPlaying: true,
        description: "Bowler",
        imgUrl: "./images/Teams/CSK/imran tahir.png",
      },
      {
        id: 8,
        playerName: "Karn Sharma",
        from: "CSK",
        price: "5 Cr",
        isPlaying: true,
        description: "Bowler",
        imgUrl: "./images/Teams/CSK/karn sharma.png",
      },
      {
        id: 9,
        playerName: "KM Asif",
        from: "CSK",
        price: "40 Lac",
        isPlaying: true,
        description: "Bowler",
        imgUrl: "./images/Teams/CSK/km asif.png",
      },
      {
        id: 10,
        playerName: "Moeen Ali",
        from: "CSK",
        price: "7 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/CSK/Moeen Ali.png",
      },

      {
        id: 11,
        playerName: "Krishnappa Gowtham",
        from: "CSK",
        price: "9.25 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/CSK/KrishnappaGowtham.png",
      },

      {
        id: 12,
        playerName: "Mitchell Santner",
        from: "CSK",
        price: "50 Lac",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/CSK/MitchellSantner.png",
      },

      {
        id: 13,
        playerName: "Narayan Jagdeeshan",
        from: "CSK",
        price: "20 Lac",
        isPlaying: true,
        description: "Wicketkeeper",
        imgUrl: "./images/Teams/CSK/narayan jagdeeshan.png",
      },

      {
        id: 14,
        playerName: "Ravindra Jadeja",
        from: "CSK",
        price: "7 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/CSK/ravindra jadeja.png",
      },

      {
        id: 15,
        playerName: "Robin Uthappa",
        from: "CSK",
        price: "3 Cr",
        isPlaying: true,
        description: "Batsman",
        imgUrl: "./images/Teams/CSK/RobinUthappa.png",
      },

      {
        id: 16,
        playerName: "Ruturaj Gaikwad",
        from: "CSK",
        price: "20 Lac",
        isPlaying: true,
        description: "Batsman",
        imgUrl: "./images/Teams/CSK/Ruturaj Gaikwad.png",
      },

      {
        id: 17,
        playerName: "Sai Kishore",
        from: "CSK",
        price: "20 Lac",
        isPlaying: true,
        description: "Bowler",
        imgUrl: "./images/Teams/CSK/sai kishore.png",
      },

      {
        id: 18,
        playerName: "Sam Curran",
        from: "CSK",
        price: "5.5 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/CSK/SamCurran.png",
      },

      {
        id: 19,
        playerName: "Shardul Thakur",
        from: "CSK",
        price: "2.6 Cr",
        isPlaying: true,
        description: "Bowler",
        imgUrl: "./images/Teams/CSK/shardul thakur.png",
      },
      {
        id: 20,
        playerName: "Suresh Raina",
        from: "CSK",
        price: "11 Cr",
        isPlaying: true,
        description: "Batsman",
        imgUrl: "./images/Teams/CSK/suresh raina.png",
      },
      {
        id: 21,
        playerName: "MS Dhoni",
        from: "CSK",
        price: "15 Cr",
        isPlaying: true,
        description: "Wicketkeeper",
        imgUrl: "./images/Teams/CSK/MS Dhoni.png",
      },
    ];
    ///////////////////////////////////
    var dcPlayers = [
      {
        id: 0,
        playerName: "Ajinkya Rahane",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/ajinkya rahane.png",
      },

      {
        id: 1,
        playerName: "Amit Sharma",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/AmitSharma.png",
      },

      {
        id: 2,
        playerName: "Anrich Nortje",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/AnrichNortje.png",
      },

      {
        id: 3,
        playerName: "Avesh Khan",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/AveshKhan.png",
      },

      {
        id: 4,
        playerName: "Axar Patel",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/AxarPatel.png",
      },
      {
        id: 5,
        playerName: "Chris Woakes",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/chris woakes.png",
      },
      {
        id: 6,
        playerName: "Kagiso Rabada",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/kagiso rabada.png",
      },
      {
        id: 7,
        playerName: "Lalit Yadav",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/lalit yadav.png",
      },
      {
        id: 8,
        playerName: "Lukman Meriwala",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/LukmanMeriwala.png",
      },
      {
        id: 9,
        playerName: "M Siddharth",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/m siddharth.png",
      },
      {
        id: 10,
        playerName: "Marcus Stoinis",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/marcus stoinis.png",
      },
      {
        id: 11,
        playerName: "Pravin Dubey",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/PravinDubey.png",
      },
      {
        id: 12,
        playerName: "Prithvi Shaw",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/PrithviShaw.png",
      },
      {
        id: 13,
        playerName: "Ravichandran Ashwin",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/ravichandran ashwin.png",
      },
      {
        id: 14,
        playerName: "Ripal Patel",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/RipalPatel.png",
      },
      {
        id: 15,
        playerName: "Rishab Pant",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/rishab pant.png",
      },
      {
        id: 16,
        playerName: "Sam Billings",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/sam billings.png",
      },
      {
        id: 17,
        playerName: "Shikhar Dhawan",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/ShikharDhawan.png",
      },
      {
        id: 18,
        playerName: "Shimron Hetmyer",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/ShimronHetmyer.png",
      },
      {
        id: 19,
        playerName: "Steve Smith",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/steve smith.png",
      },
      {
        id: 20,
        playerName: "Tom Curran",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/TomCurran.png",
      },
      {
        id: 21,
        playerName: "Umesh Yadav",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/UmeshYadav.png",
      },
      {
        id: 20,
        playerName: "Vishnu Vinod",
        from: "DC",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/DC/vishnu vinod.png",
      },
    ];
    ///////////////////////////////////////////////
    var kkrPlayers = [
      {
        id: 0,
        playerName: "Andre Russell",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/AndreRussell.png",
      },
      {
        id: 1,
        playerName: "Ben Cutting",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/ben cutting.png",
      },
      {
        id: 2,
        playerName: "Dinesh Karthik",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/DineshKarthik.png",
      },
      {
        id: 3,
        playerName: "Eoin Morgan",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/eoin morgan.png",
      },
      {
        id: 4,
        playerName: "Gurkeerat Mann Singh",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/GurkeeratMannSingh.png",
      },
      {
        id: 5,
        playerName: "Harbhajan Singh",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/HarbhajanSingh.png",
      },
      {
        id: 6,
        playerName: "Kamlesh Nagarkoti",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/KamleshNagarkoti.png",
      },
      {
        id: 7,
        playerName: "Karun Nair",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/karun nair.png",
      },
      {
        id: 8,
        playerName: "Kuldeep Yadav",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/kuldeep yadav.png",
      },
      {
        id: 9,
        playerName: "Lockie Ferguson",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/lockie ferguson.png",
      },
      {
        id: 10,
        playerName: "Nitish Rana",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/NitishRana.png",
      },
      {
        id: 11,
        playerName: "Pat Cummins",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/PatCummins.png",
      },
      {
        id: 12,
        playerName: "Pawan Negi",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/PawanNegi.png",
      },
      {
        id: 13,
        playerName: "Prasidh Krishna",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/PrasidhKrishna.png",
      },
      {
        id: 14,
        playerName: "Rahul Tripathi",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/RahulTripathi.png",
      },
      {
        id: 15,
        playerName: "Sandeep Warrier",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/sandeep warrier.png",
      },
      {
        id: 16,
        playerName: "Shakib Al Hasan",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/shakib al hasan.png",
      },
      {
        id: 17,
        playerName: "Sheldon Jackson",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/SheldonJackson.png",
      },
      {
        id: 18,
        playerName: "Shivam Mavi",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/shivam mavi.png",
      },
      {
        id: 19,
        playerName: "Shubham Gill",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/ShubhamGill.png",
      },
      {
        id: 20,
        playerName: "Sunil Narine",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/sunil narine.png",
      },
      {
        id: 21,
        playerName: "Tim Seifert",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/tim seifert.png",
      },
      {
        id: 22,
        playerName: "Vaibhav Arora",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/vaibhav arora.png",
      },
      {
        id: 23,
        playerName: "Varun Chakaravarthy",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/VarunChakaravarthy.png",
      },
      {
        id: 24,
        playerName: "Venkatesh Iyer",
        from: "KKR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/KKR/VenkateshIyer.png",
      },
    ];
    /////////////////////////////////////////////
    var miPlayers = [
      {
        id: 0,
        playerName: "Adam Milne",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/AdamMilne.png",
      },
      {
        id: 1,
        playerName: "Aditya Tare",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/AdityaTare.png",
      },
      {
        id: 2,
        playerName: "Anmolpreet Singh",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/anmolpreet singh.png",
      },
      {
        id: 3,
        playerName: "Anukul Roy",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/AnukulRoy.png",
      },
      {
        id: 4,
        playerName: "Arjun Tendulkar",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/arjun tendulkar.png",
      },
      {
        id: 5,
        playerName: "Chris Lynn",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/ChrisLynn.png",
      },
      {
        id: 6,
        playerName: "Dhawal Kulkarni",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/DhawalKulkarni.png",
      },
      {
        id: 7,
        playerName: "Hardik Pandya",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/HardikPandya.png",
      },
      {
        id: 8,
        playerName: "Ishan Kishan",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/IshanKishan.png",
      },
      {
        id: 9,
        playerName: "Jasprit Bumrah",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/JaspritBumrah.png",
      },
      {
        id: 10,
        playerName: "Jayant Yadav",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/jayant yadav.png",
      },
      {
        id: 11,
        playerName: "Jimmy Neeshan",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/jimmy neeshan.png",
      },
      {
        id: 12,
        playerName: "Krunal Pandya",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/KrunalPandya.png",
      },
      {
        id: 13,
        playerName: "Marco Jansen",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/MarcoJansen.png",
      },
      {
        id: 14,
        playerName: "Moshin Khan",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/moshin khan.png",
      },
      {
        id: 15,
        playerName: "Nathan Coulter Nile",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/nathan coulter nile.png",
      },
      {
        id: 16,
        playerName: "Piyush Chawla",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/piyush chawla.png",
      },
      {
        id: 17,
        playerName: "Quinton De Kock",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/quinton de kock.png",
      },
      {
        id: 18,
        playerName: "Rahul Chahar",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/RahulChahar.png",
      },
      {
        id: 19,
        playerName: "Rohit Sharma",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/rohit sharma.png",
      },
      {
        id: 20,
        playerName: "Saurabh Tiwary",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/SaurabhTiwary.png",
      },
      {
        id: 21,
        playerName: "Suryakumar Yadav",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/SuryakumarYadav.png",
      },
      {
        id: 22,
        playerName: "Trent Boult",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/trent boult.png",
      },
      {
        id: 23,
        playerName: "Yudhvir Charak",
        from: "MI",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/MI/YudhvirCharak.png",
      },
    ];
    //////////////////////////////////////////
    var pkPlayers = [
      {
        id: 0,
        playerName: "Arshdeep Singh",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/ArshdeepSingh.png",
      },
      {
        id: 1,
        playerName: "Chris Gayle",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/ChrisGayle.png",
      },
      {
        id: 2,
        playerName: "Chris Jordan",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/ChrisJordan.png",
      },
      {
        id: 3,
        playerName: "Darshan Nalkande",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/DarshanNalkande.png",
      },
      {
        id: 4,
        playerName: "Dawid Malan",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/DawidMalan.png",
      },
      {
        id: 5,
        playerName: "Deepak Hooda",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/DeepakHooda.png",
      },
      {
        id: 6,
        playerName: "Fabian Allen",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/FabianAllen.png",
      },
      {
        id: 7,
        playerName: "Harpreet Brar",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/HarpreetBrar.png",
      },
      {
        id: 8,
        playerName: "Ishan Porel",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/IshanPorel.png",
      },
      {
        id: 9,
        playerName: "Jalaj Saxena",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/JalajSaxena.png",
      },
      {
        id: 10,
        playerName: "Jhye Richardson",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/JhyeRichardson.png",
      },
      {
        id: 11,
        playerName: "KL Rahul",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/KLRahul.png",
      },
      {
        id: 12,
        playerName: "Mandeep Singh",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/MandeepSingh.png",
      },
      {
        id: 13,
        playerName: "Mayank Agarwal",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/MayankAgarwal.png",
      },
      {
        id: 14,
        playerName: "Mohammad Shami",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/MohammadShami.png",
      },
      {
        id: 15,
        playerName: "Moises Henriques",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/MoisesHenriques.png",
      },
      {
        id: 16,
        playerName: "Murugan Ashwin",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/MuruganAshwin.png",
      },
      {
        id: 17,
        playerName: "Nicholas Pooran",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/NicholasPooran.png",
      },
      {
        id: 18,
        playerName: "Prabhshimran Singh",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/Prabhshimran Singh.png",
      },
      {
        id: 19,
        playerName: "Ravi Bishnoi",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/RaviBishnoi.png",
      },
      {
        id: 20,
        playerName: "Riley Meredith",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/RileyMeredith.png",
      },
      {
        id: 21,
        playerName: "Sarfaraz Khan",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/SarfarazKhan.png",
      },
      {
        id: 22,
        playerName: "Saurabh Kumar",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/SaurabhKumar.png",
      },
      {
        id: 23,
        playerName: "Shahrukh Khan",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/ShahrukhKhan.png",
      },
      {
        id: 24,
        playerName: "Utkarsh Singh",
        from: "PK",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/PK/UtkarshSingh.png",
      },
    ];
    /////////////////////////////////////////
    var rcbPlayers = [
      {
        id: 0,
        playerName: "AB de Villiers",
        from: "RCB",
        price: "11 Cr",
        isPlaying: true,
        description: "Batsman/Wicket-keeper",
        imgUrl: "./images/Teams/RCB/ABdeVilliers.png",
      },
      {
        id: 1,
        playerName: "Adam Zampa",
        from: "RCB",
        price: "1.5 Cr",
        isPlaying: true,
        description: "Bowler",
        imgUrl: "./images/Teams/RCB/AdamZampa.png",
      },
      {
        id: 2,
        playerName: "Dan Christian",
        from: "RCB",
        price: "75 Lac",
        isPlaying: false,
        description: "All-rounder",
        imgUrl: "./images/Teams/RCB/DanChristian.png",
      },
      {
        id: 3,
        playerName: "Daniel Sams",
        from: "RCB",
        price: "30 Lac",
        isPlaying: false,
        description: "All-rounder",
        imgUrl: "./images/Teams/RCB/DanielSams.png",
      },
      {
        id: 4,
        playerName: "Devdutt Padikkal",
        from: "RCB",
        price: "20 Lac",
        isPlaying: true,
        description: "Batsman",
        imgUrl: "./images/Teams/RCB/DevduttPadikkal.png",
      },
      {
        id: 5,
        playerName: "Finn Allen",
        from: "RCB",
        price: "20 Lac Cr",
        isPlaying: false,
        description: "Batsman",
        imgUrl: "./images/Teams/RCB/FinnAllen.png",
      },
      {
        id: 6,
        playerName: "Glenn Maxwell",
        from: "RCB",
        price: "14.25 Cr",
        isPlaying: false,
        description: "Batsman",
        imgUrl: "./images/Teams/RCB/GlennMaxwell.png",
      },
      {
        id: 7,
        playerName: "Harshal Patel",
        from: "RCB",
        price: "20 Lac",
        isPlaying: false,
        description: "Bowler",
        imgUrl: "./images/Teams/RCB/HarshalPatel.png",
      },
      {
        id: 8,
        playerName: "Kane Richardson",
        from: "RCB",
        price: "4 Cr",
        isPlaying: true,
        description: "Bowler",
        imgUrl: "./images/Teams/RCB/KaneRichardson.png",
      },
      {
        id: 9,
        playerName: "KS Bharat",
        from: "RCB",
        price: "20 Lac",
        isPlaying: false,
        description: "Batsman/Wicketkeeper",
        imgUrl: "./images/Teams/RCB/KSBharat.png",
      },
      {
        id: 10,
        playerName: "Yuzvendra Chahal",
        from: "RCB",
        price: "6 Cr",
        isPlaying: true,
        description: "Bowler",
        imgUrl: "./images/Teams/RCB/YuzvendraChahal.png",
      },
      {
        id: 11,
        playerName: "Kyle Jamieson",
        from: "RCB",
        price: "15 Cr",
        isPlaying: false,
        description: "Bowler",
        imgUrl: "./images/Teams/RCB/KyleJamieson.png",
      },
      {
        id: 12,
        playerName: "Mohammed Azharuddeen",
        from: "RCB",
        price: "20 Lac",
        isPlaying: false,
        description: "Wicketkeeper",
        imgUrl: "./images/Teams/RCB/MohammedAzharuddeen.png",
      },
      {
        id: 13,
        playerName: "Mohammed Siraj",
        from: "RCB",
        price: "2.6 Cr",
        isPlaying: true,
        description: "Bowler",
        imgUrl: "./images/Teams/RCB/MohammedSiraj.png",
      },
      {
        id: 14,
        playerName: "Navdeep Saini",
        from: "RCB",
        price: "3 Cr",
        isPlaying: true,
        description: "Bowler",
        imgUrl: "./images/Teams/RCB/NavdeepSaini.png",
      },
      {
        id: 15,
        playerName: "Pavan Deshpande",
        from: "RCB",
        price: "20 Lac",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RCB/PavanDeshpande.png",
      },
      {
        id: 16,
        playerName: "Rajat Patidar",
        from: "RCB",
        price: "20 Lac",
        isPlaying: false,
        description: "Batsman",
        imgUrl: "./images/Teams/RCB/RajatPatidar.png",
      },
      {
        id: 17,
        playerName: "Sachin Baby",
        from: "RCB",
        price: "20 Lac",
        isPlaying: false,
        description: "Batsman",
        imgUrl: "./images/Teams/RCB/SachinBaby.png",
      },
      {
        id: 18,
        playerName: "Shahbaz Ahmed",
        from: "RCB",
        price: "20 Lac",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RCB/ShahbazAhmed.png",
      },
      {
        id: 19,
        playerName: "Suyash Prabhudessai",
        from: "RCB",
        price: "20 Lac",
        isPlaying: false,
        description: "Batsman",
        imgUrl: "./images/Teams/RCB/SuyashPrabhudessai.png",
      },
      {
        id: 20,
        playerName: "Virat Kohli",
        from: "RCB",
        price: "17 Cr",
        isPlaying: true,
        description: "Batsman",
        imgUrl: "./images/Teams/RCB/ViratKohli.png",
      },
      {
        id: 21,
        playerName: "Washington Sundar",
        from: "RCB",
        price: "3.2 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RCB/WashingtonSundar.png",
      },
    ];
    /////////////////////////////////////////
    var rrPlayers = [
      {
        id: 0,
        playerName: "Akash Singh",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/AkashSingh.png",
      },
      {
        id: 1,
        playerName: "Andrew Tye",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/AndrewTye.png",
      },
      {
        id: 2,
        playerName: "Anuj Rawat",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/AnujRawat.png",
      },
      {
        id: 3,
        playerName: "Ben Stokes",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/BenStokes.png",
      },
      {
        id: 4,
        playerName: "Chetan Sakariya",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/ChetanSakariya.png",
      },
      {
        id: 5,
        playerName: "Chris Morris",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/ChrisMorris.png",
      },
      {
        id: 6,
        playerName: "David Miller",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/DavidMiller.png",
      },
      {
        id: 7,
        playerName: "Jaydev Unadkat",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/JaydevUnadkat.png",
      },
      {
        id: 8,
        playerName: "Jos Buttler",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/JosButtler.png",
      },
      {
        id: 9,
        playerName: "Kartik Tyagi",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/KartikTyagi.png",
      },
      {
        id: 10,
        playerName: "KC Cariappa",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/KCCariappa.png",
      },
      {
        id: 11,
        playerName: "Kuldip Yadav",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/KuldipYadav.png",
      },
      {
        id: 12,
        playerName: "Liam Livingstone",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/LiamLivingstone.png",
      },
      {
        id: 13,
        playerName: "Mahipal Lomror",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/MahipalLomror.png",
      },
      {
        id: 14,
        playerName: "Manan Vohra",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/MananVohra.png",
      },
      {
        id: 15,
        playerName: "Mayank Markande",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/MayankMarkande.png",
      },
      {
        id: 16,
        playerName: "Mustafizur Rahman",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/MustafizurRahman.png",
      },
      {
        id: 17,
        playerName: "Rahul Tewatia",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/RahulTewatia.png",
      },
      {
        id: 18,
        playerName: "Yashasvi Jaiswal",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/YashasviJaiswal.png",
      },
      {
        id: 19,
        playerName: "Riyan Parag",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/RiyanParag.png",
      },
      {
        id: 20,
        playerName: "Sanju Samson",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/SanjuSamson.png",
      },
      {
        id: 21,
        playerName: "Shivam Dube",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/ShivamDube.png",
      },
      {
        id: 22,
        playerName: "Shreyas Gopal",
        from: "RR",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/RR/ShreyasGopal.png",
      },
    ];
    ////////////////////////////////////////
    var shPlayers = [
      {
        id: 0,
        playerName: "Abdul Samad",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/AbdulSamad.png",
      },
      {
        id: 1,
        playerName: "Abhishek Sharma",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/AbhishekSharma.png",
      },
      {
        id: 2,
        playerName: "Basil Thampi",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/BasilThampi.png",
      },
      {
        id: 3,
        playerName: "Bhuvneshwar Kumar",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/BhuvneshwarKumar.png",
      },
      {
        id: 4,
        playerName: "David Warner",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/DavidWarner.png",
      },
      {
        id: 5,
        playerName: "Jagadeesha Suchith",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/JagadeeshaSuchith.png",
      },
      {
        id: 6,
        playerName: "Jason Holder",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/JasonHolder.png",
      },
      {
        id: 7,
        playerName: "Jonny Bairstow",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/JonnyBairstow.png",
      },
      {
        id: 8,
        playerName: "Kane Williamson",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/KaneWilliamson.png",
      },
      {
        id: 9,
        playerName: "Kedar Jadhav",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/KedarJadhav.png",
      },
      {
        id: 10,
        playerName: "Khaleel Ahmed",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/KhaleelAhmed.png",
      },
      {
        id: 11,
        playerName: "Manish Pandey",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/ManishPandey.png",
      },
      {
        id: 12,
        playerName: "Mohammad Nabi",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/MohammadNabi.png",
      },
      {
        id: 13,
        playerName: "Mujeeb Ur Rahman",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/MujeebUrRahman.png",
      },
      {
        id: 14,
        playerName: "Priyam Garg",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/PriyamGarg.png",
      },
      {
        id: 15,
        playerName: "Rashid Khan",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/RashidKhan.png",
      },
      {
        id: 16,
        playerName: "Sandeep Sharma",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/SandeepSharma.png",
      },
      {
        id: 17,
        playerName: "Shabaz Nadeem",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/ShabazNadeem.png",
      },
      {
        id: 18,
        playerName: "Shiddarth Kaul",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/ShiddarthKaul.png",
      },
      {
        id: 19,
        playerName: "Shreevats Goswami",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/ShreevatsGoswami.png",
      },
      {
        id: 20,
        playerName: "T Natarajan",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/TNatarajan.png",
      },
      {
        id: 21,
        playerName: "Vijay Shankar",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/VijayShankar.png",
      },
      {
        id: 22,
        playerName: "Virat Singh",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/ViratSingh.png",
      },
      {
        id: 23,
        playerName: "Wriddhiman Saha",
        from: "SH",
        price: "6.50 Cr",
        isPlaying: true,
        description: "All-rounder",
        imgUrl: "./images/Teams/SH/WriddhimanSaha.png",
      },
    ];
    ////////////////////////////////////////
    var teams = [
      {
        id: 0,
        teamName: "Chennai Super Kings",
        key: "CSK",
        noOfWins: 3,
        topBatsman: "Suresh Raina",
        topBowler: "Dwayne Bravo",
        totalPlayer: cskPlayers.length,
        teamLogoUrl: "./images/Teams/CSK/csk-hd-logo-2020.webp",
        players: cskPlayers,
      },
      {
        id: 1,
        teamName: "Delhi Capitals",
        key: "DC",
        noOfWins: 0,
        topBatsman: "Shikhar Dhawan",
        topBowler: "Umesh Yadav",
        totalPlayer: dcPlayers.length,
        teamLogoUrl: "./images/Teams/DC/Delhi-Capital-_Logo.webp",
        players: dcPlayers,
      },

      {
        id: 2,
        teamName: "Kolkata Knight Riders",
        key: "KKR",
        noOfWins: 2,
        topBatsman: "Andre Russell",
        topBowler: "Varun Chakravarthy",
        totalPlayer: kkrPlayers.length,
        teamLogoUrl: "./images/Teams/KKR/KKR-Logo.webp",
        players: kkrPlayers,
      },

      {
        id: 3,
        teamName: "Mumbai Indians",
        key: "MI",
        noOfWins: 5,
        topBatsman: "Kieron Pollard",
        topBowler: "Jasprit Bumrah",
        totalPlayer: miPlayers.length,
        teamLogoUrl: "./images/Teams/MI/mumbai-indians-png-logo-2020.webp",
        players: miPlayers,
      },

      {
        id: 4,
        teamName: "Punjab Kings",
        key: "PK",
        noOfWins: 0,
        topBatsman: "KL Rahul",
        topBowler: "Mohammad Shami",
        totalPlayer: pkPlayers.length,
        teamLogoUrl: "./images/Teams/PK/punjab-kings-logo-01.webp",
        players: pkPlayers,
      },

      {
        id: 5,
        teamName: "Royal Challengers Bangalore",
        key: "RCB",
        noOfWins: 0,
        topBatsman: "AB de Villiers",
        topBowler: "Yuzvendra Chahal",
        totalPlayer: rcbPlayers.length,
        teamLogoUrl: "./images/Teams/RCB/RCB-png-logo-2020.webp",
        players: rcbPlayers,
      },

      {
        id: 6,
        teamName: "Rajasthan Royals",
        key: "RR",
        noOfWins: 1,
        topBatsman: "Sanju Samson",
        topBowler: "Jofra Archer",
        totalPlayer: rrPlayers.length,
        teamLogoUrl: "./images/Teams/RR/RR-Logo.webp",
        players: rrPlayers,
      },

      {
        id: 7,
        teamName: "Sunrise Hyderabad",
        key: "SH",
        noOfWins: 1,
        topBatsman: "David Warner",
        topBowler: "Rashid Khan",
        totalPlayer: 24,
        teamLogoUrl: "./images/Teams/SH/SRH-Logo-Png-.webp",
        players: shPlayers,
      },
    ];
    return teams;
  }
});
